ALTER TABLE papers
  ADD COLUMN IF NOT EXISTS ce_override BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS ce_override_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS ce_override_by UUID REFERENCES users(id);
