ALTER TABLE papers
  ADD COLUMN IF NOT EXISTS is_special_issue BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS previously_submitted TEXT NOT NULL DEFAULT 'no',
  ADD COLUMN IF NOT EXISTS preprint_available BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS human_subjects BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS data_sharing TEXT NOT NULL DEFAULT 'on_request';
